import { hashSeed, mulberry32, randomSeed } from '../tarot/draw'

/**
 * The Book of Answers and the Book of Questions, LazyOracle editions. Both
 * corpora are original: short answers in the spirit of the classic "ask a
 * yes/no question, open the book" ritual, and reflective questions to sit
 * with. The pick is seeded so a page can be revisited by its number.
 */

export interface Page {
  number: number
  en: string
  zh: string
}

const ANSWERS: [string, string][] = [
  ['Yes.', '是的。'],
  ['Not yet.', '还不是时候。'],
  ['Only if you mean it.', '只有当你是认真的。'],
  ['Ask again after you have slept on it.', '睡一觉再问一次。'],
  ['Let it come to you.', '让它自己来找你。'],
  ['Take the first small step today.', '今天就迈出第一小步。'],
  ['You already know.', '你其实已经知道答案了。'],
  ['Wait for a clearer sign.', '等一个更清楚的信号。'],
  ['Absolutely.', '当然。'],
  ['Not this way.', '不是这条路。'],
  ['Trust the slower option.', '选那个慢一点的。'],
  ['Say it out loud first.', '先把它说出口。'],
  ['Someone else holds the key.', '钥匙在别人手里。'],
  ['Do it before the month ends.', '月底前去做。'],
  ['It will cost more than you think.', '代价比你想的要大。'],
  ['Follow the money; then follow your gut.', '先看利害，再听直觉。'],
  ['Change the question.', '换个问题。'],
  ['The answer is in the details you skipped.', '答案在你跳过的细节里。'],
  ['Go, and keep your options open.', '去吧，但留条后路。'],
  ['A firm no.', '坚决不。'],
  ['Give it one more week.', '再给它一周。'],
  ['Be the one who reaches out.', '做主动伸手的那个人。'],
  ['You will be glad you tried.', '你会庆幸自己试过。'],
  ['Protect your mornings.', '守住你的早晨。'],
  ['Finish what is already on the table.', '先把手上的事做完。'],
  ['Only with help.', '需要人帮忙才行。'],
  ['Expect a surprise.', '会有意外。'],
  ['Read the fine print.', '看清楚小字。'],
  ['Yes, but not alone.', '可以，但别一个人做。'],
  ['Wrong door, right building.', '门错了，楼没错。'],
  ['Watch what they do, not what they say.', '看他们做什么，别听他们说什么。'],
  ['Rest first.', '先休息。'],
  ['It is smaller than it feels.', '事情比你感觉的要小。'],
  ['The timing is finally right.', '时机终于对了。'],
  ['Let someone else go first.', '让别人先走一步。'],
  ['Choose the kinder option.', '选更善良的那个。'],
  ['Prepare, then leap.', '准备好，然后跳。'],
  ['Not in this form.', '不是以这种形式。'],
  ['Write it down and decide tomorrow.', '写下来，明天再决定。'],
  ['Say yes to the invitation.', '答应那个邀请。'],
  ['Keep it private for now.', '暂时别声张。'],
  ['Simplify.', '化繁为简。'],
  ['You are asking the wrong person.', '你问错人了。'],
  ['It has already begun.', '它已经开始了。'],
  ['Count the cost twice.', '把代价再算一遍。'],
  ['Move toward the light.', '朝亮的地方走。'],
  ['Don\'t force it.', '别硬来。'],
  ['A door will open on its own.', '门会自己打开。'],
  ['Stop apologising.', '别再道歉了。'],
  ['Make the call.', '打那个电话。'],
  ['Pay attention to who shows up.', '留意谁出现了。'],
  ['Your first instinct was correct.', '你的第一直觉是对的。'],
  ['Wait until it is boring.', '等到它变得平淡再说。'],
  ['Turn it into a game.', '把它变成一场游戏。'],
  ['Only part of it.', '只有一部分。'],
  ['Try the opposite.', '试试反过来。'],
  ['Start over, smaller.', '重新开始，规模小一点。'],
  ['Be generous.', '大方一点。'],
  ['Look closer to home.', '往身边看。'],
  ['Keep going.', '继续。'],
  ['The season has passed; plant for the next.', '季节已过，为下一季播种。'],
  ['Yes, and soon.', '是的，而且很快。'],
  ['Hold your ground.', '守住立场。'],
  ['Apologise first.', '先道歉。'],
  ['Let the dust settle.', '等尘埃落定。'],
  ['Ask for exactly what you want.', '直接说出你想要的。'],
  ['It is not about you.', '这件事和你无关。'],
  ['Learn the rules before breaking them.', '先学会规则，再打破它。'],
  ['A quiet yes.', '一个安静的“是”。'],
  ['Postpone it once, not twice.', '推迟一次可以，别推第二次。'],
  ['Bring a friend.', '带上一个朋友。'],
  ['Spend the money.', '花这笔钱。'],
  ['Save the money.', '存下这笔钱。'],
  ['Trust the process, question the timeline.', '相信过程，怀疑时间表。'],
  ['Listen more than you speak this week.', '这周多听少说。'],
  ['Walk away with grace.', '体面地离开。'],
  ['Stay one more round.', '再留一轮。'],
  ['Let them decide.', '让他们决定。'],
  ['Your effort will be noticed.', '你的努力会被看见。'],
  ['Not everyone needs to agree.', '不是所有人都需要同意。'],
  ['The obstacle is the lesson.', '那道障碍就是这一课。'],
  ['Go slowly and you will arrive.', '慢慢走，就会到。'],
  ['Clean your desk first.', '先把桌子收拾干净。'],
  ['You can afford to be patient.', '你耐心得起。'],
  ['Do not sign yet.', '先别签。'],
  ['Celebrate what is already done.', '庆祝已经完成的部分。'],
  ['Choose depth over speed.', '要深度，不要速度。'],
  ['Make room for it.', '给它腾出空间。'],
  ['One honest conversation will settle it.', '一次坦诚的谈话就能解决。'],
  ['Leave a little unfinished.', '留一点没做完。'],
  ['The best answer is a good question.', '最好的答案是一个好问题。'],
  ['Stand still; the view is changing.', '站着别动，风景在变。'],
  ['Yes, if you can laugh about it.', '可以，只要你能一笑置之。'],
  ['Nobody is watching as closely as you think.', '没人像你以为的那样盯着你。'],
  ['Choose what you can maintain.', '选你能长期维持的。'],
  ['Let go of the version you planned.', '放下你原本计划的那个版本。'],
  ['Good things are gathering.', '好事正在聚集。'],
  ['Lower the stakes.', '把赌注放低。'],
  ['Double-check the date.', '再核对一下日期。'],
  ['Begin with gratitude.', '从感谢开始。'],
  ['Definitely not today.', '今天绝对不行。'],
  ['Wear the good shoes.', '穿那双好鞋。'],
  ['Accept the compliment.', '接受那句夸奖。'],
  ['Turn the page.', '翻篇。'],
  ['Meet them halfway.', '各退一步。'],
  ['Let the silence do the work.', '让沉默去发挥作用。'],
  ['Practise, don\'t plan.', '去练，别只计划。'],
  ['A short trip will help.', '一次短途旅行会有帮助。'],
  ['Fix the smallest thing first.', '先修最小的那件。'],
  ['Someone is waiting for you to ask.', '有人在等你开口。'],
  ['Be early.', '早到。'],
  ['Read it again tomorrow.', '明天再读一遍。'],
  ['It is worth the wait.', '值得等。'],
  ['Nothing needs to change today.', '今天什么都不用改。'],
  ['Pick the one that makes you curious.', '选让你好奇的那个。'],
  ['Give without keeping score.', '给予，不记账。'],
  ['Stay in the room.', '留在房间里。'],
  ['Say less.', '少说。'],
  ['Look up.', '抬头看看。'],
]

const QUESTIONS: [string, string][] = [
  ['What would you do this week if no one could see the result?', '如果没人看得到结果，这周你会做什么？'],
  ['Which of your habits would your ten-year-old self be proud of?', '你十岁时的自己会为你现在的哪个习惯骄傲？'],
  ['What are you pretending not to know?', '你在假装不知道什么？'],
  ['Who would you call if you had only one call?', '如果只能打一个电话，你会打给谁？'],
  ['What have you been carrying that was never yours?', '你一直背着的东西里，哪件从来不属于你？'],
  ['If your fear had a name, what would it ask for?', '如果你的恐惧有名字，它会向你要什么？'],
  ['What did you love before you learned to be good at things?', '在你学会“擅长”之前，你爱做什么？'],
  ['What would make tomorrow feel like a gift?', '什么会让明天像一份礼物？'],
  ['Where in your life are you waiting for permission?', '你在生活的哪个地方还在等待许可？'],
  ['Which conversation are you avoiding, and what does that cost you?', '你在回避哪一次对话？这让你付出了什么？'],
  ['What is enough?', '多少才算够？'],
  ['What do you want to be true about you in five years?', '五年后，你希望关于自己的什么是真的？'],
  ['When did you last change your mind about something important?', '你上一次在重要的事上改变想法是什么时候？'],
  ['What would you attempt if failure were quiet and private?', '如果失败是安静而私密的，你会尝试什么？'],
  ['Whose approval are you still working for?', '你还在为谁的认可而努力？'],
  ['What small kindness did you receive recently and not acknowledge?', '最近你收到过哪份小小的善意，却没有回应？'],
  ['If today repeated forever, what would you fix first?', '如果今天永远重复，你会先修哪一件事？'],
  ['What are you loyal to that no longer deserves it?', '你对什么保持着忠诚，而它已不再值得？'],
  ['What do you know how to do that you have never taught anyone?', '你会做什么，却从未教过别人？'],
  ['Which memory would you keep if you could keep only one?', '如果只能保留一段记忆，你会留哪一段？'],
  ['What would you stop doing if you trusted yourself more?', '如果你更信任自己，你会停止做什么？'],
  ['Where does your attention go when you are not steering it?', '当你不刻意引导时，注意力会跑去哪里？'],
  ['What are you building, and who is it for?', '你在建造什么？为了谁？'],
  ['How do you want to be remembered by someone you met only once?', '你希望只见过一面的人怎么记得你？'],
  ['What is the most useful thing you learned from being wrong?', '你从犯错中学到的最有用的东西是什么？'],
  ['If your week had a title, what would it be?', '如果这一周有个标题，会是什么？'],
  ['What is the question you keep answering with "later"?', '你一直用“以后再说”回答的问题是什么？'],
  ['What would rest look like if it were not a reward?', '如果休息不是奖励，它会是什么样子？'],
  ['Who taught you how to love, and what did they get wrong?', '谁教会了你如何去爱？他们哪里教错了？'],
  ['What would you do with an extra hour every day?', '每天多出一小时，你会用来做什么？'],
  ['What are you ready to forgive?', '你准备好原谅什么了？'],
  ['Which of your beliefs would embarrass you if said aloud?', '你的哪个信念说出来会让你难为情？'],
  ['What do you owe your future self?', '你欠未来的自己什么？'],
  ['Where do you feel most like yourself?', '在哪里你最像你自己？'],
  ['What is the bravest thing you did this year?', '今年你做过最勇敢的事是什么？'],
  ['What would you say if you were sure to be understood?', '如果确定会被理解，你会说什么？'],
  ['Which door did you close too early?', '你太早关上了哪扇门？'],
  ['What are you curious about that has no practical use?', '你对什么毫无用处的东西感到好奇？'],
  ['What does your body know that your calendar ignores?', '你的身体知道什么，而日程表在无视？'],
  ['What would you protect at any cost?', '你会不惜一切保护什么？'],
  ['When did you last make something with your hands?', '你上一次亲手做东西是什么时候？'],
  ['Who needs to hear from you today?', '今天谁需要听到你的消息？'],
  ['What is one thing you could decide right now?', '有什么事你现在就可以决定？'],
  ['What story about yourself are you ready to retire?', '你准备让哪个关于自己的故事退休？'],
  ['What would you do differently if you knew it would work?', '如果知道一定会成功，你会有什么不同的做法？'],
  ['Which compliment do you find hardest to believe?', '哪句夸奖你最难相信？'],
  ['What is your favourite kind of silence?', '你最喜欢哪一种安静？'],
  ['What have you outgrown without noticing?', '你在不知不觉中已经长大到不再需要什么？'],
  ['If you could send one sentence to yourself a year ago, what would it be?', '如果能给一年前的自己发一句话，会是什么？'],
  ['What is the next right thing?', '接下来那件对的事是什么？'],
  ['Where are you spending courage you do not need to?', '你在哪里花着不必要的勇气？'],
  ['What would you like to be asked?', '你希望被问到什么？'],
  ['Who is easier to love from a distance?', '谁是隔着距离更容易去爱的人？'],
  ['What would a generous reading of your situation say?', '如果宽厚地看待你的处境，会怎么说？'],
  ['What is the smallest promise you could keep today?', '今天你能守住的最小的承诺是什么？'],
  ['What do you keep returning to?', '你总是回到什么上面？'],
  ['What deserves a second look?', '什么值得再看一眼？'],
  ['When are you most patient, and why?', '你什么时候最有耐心？为什么？'],
  ['What would you teach if you had one hour and a room full of strangers?', '如果只有一小时和一屋子陌生人，你会教什么？'],
  ['What are you no longer afraid of?', '你已经不再害怕什么了？'],
]

export const answerBook: Page[] = ANSWERS.map(([en, zh], index) => ({ number: index + 1, en, zh }))
export const questionBook: Page[] = QUESTIONS.map(([en, zh], index) => ({ number: index + 1, en, zh }))

export interface Opening {
  book: 'answers' | 'questions'
  seed: number
  page: Page
  question: string
  openedAt: string
}

/** Opens a page. With a seed the same page comes back; with a question, the seed mixes in its text. */
export function openBook(book: 'answers' | 'questions', options: { seed?: number; question?: string; now?: Date } = {}): Opening {
  const pages = book === 'answers' ? answerBook : questionBook
  const seed = options.seed ?? (randomSeed() ^ hashSeed(options.question ?? '')) >>> 0
  const next = mulberry32(seed)
  const page = pages[Math.floor(next() * pages.length)]
  return { book, seed, page, question: (options.question ?? '').trim(), openedAt: (options.now ?? new Date()).toISOString() }
}
