"""Generate the interface strings for both native apps from one catalogue.

The interface catalogue is `i18n/app/strings.json`; computed reading text is
translated for display using `i18n/app/content.json`. Both contain all eleven
languages. Engine identifiers and the original facts remain unchanged.

    python3 tools/auspice-build-strings.py
"""
import json
import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parent.parent
CATALOGUE = json.loads((REPO / "i18n/app/strings.json").read_text())
LANGS = CATALOGUE["languages"]
STRINGS = CATALOGUE["strings"]

# Fallback vocabulary for the almanac.
GLOSSARY = json.loads((REPO / "i18n/app/almanac-terms.json").read_text())["terms"]

NAMES = {
    "en": "English", "zh-Hans": "简体中文", "zh-Hant": "繁體中文", "ja": "日本語",
    "ko": "한국어", "vi": "Tiếng Việt", "es": "Español", "fr": "Français",
    "de": "Deutsch", "ru": "Русский", "ar": "العربية",
}
RTL = {"ar"}


def swift_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def kotlin_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'


def build_swift() -> str:
    lines = [
        "// Generated by tools/auspice-build-strings.py from i18n/app/strings.json.",
        "// Edit the catalogue, not this file.",
        "import SwiftUI",
        "",
        "enum Catalogue {",
        "    static let languages: [(code: String, name: String)] = [",
    ]
    for code in LANGS:
        lines.append(f"        ({swift_quote(code)}, {swift_quote(NAMES[code])}),")
    lines += [
        "    ]",
        "",
        f"    static let rightToLeft: Set<String> = [{', '.join(swift_quote(c) for c in sorted(RTL))}]",
        "",
        "    static let table: [String: [String: String]] = [",
    ]
    for key in sorted(STRINGS):
        pairs = ", ".join(f"{swift_quote(code)}: {swift_quote(STRINGS[key][code])}" for code in LANGS)
        lines.append(f"        {swift_quote(key)}: [{pairs}],")
    lines += ["    ]", "", "    static let glossary: [String: [String: String]] = ["]
    for term in sorted(GLOSSARY):
        pairs = ", ".join(f"{swift_quote(code)}: {swift_quote(GLOSSARY[term][code])}" for code in LANGS)
        lines.append(f"        {swift_quote(term)}: [{pairs}],")
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def build_kotlin() -> str:
    lines = [
        "// Generated by tools/auspice-build-strings.py from i18n/app/strings.json.",
        "// Edit the catalogue, not this file.",
        "package art.lazying.auspice",
        "",
        "object Catalogue {",
        "    val languages: List<Pair<String, String>> = listOf(",
    ]
    for code in LANGS:
        lines.append(f"        {kotlin_quote(code)} to {kotlin_quote(NAMES[code])},")
    lines += [
        "    )",
        "",
        f"    val rightToLeft: Set<String> = setOf({', '.join(kotlin_quote(c) for c in sorted(RTL))})",
        "",
        "    val table: Map<String, Map<String, String>> = mapOf(",
    ]
    for key in sorted(STRINGS):
        pairs = ", ".join(f"{kotlin_quote(code)} to {kotlin_quote(STRINGS[key][code])}" for code in LANGS)
        lines.append(f"        {kotlin_quote(key)} to mapOf({pairs}),")
    lines += ["    )", "", "    val glossary: Map<String, Map<String, String>> = mapOf("]
    for term in sorted(GLOSSARY):
        pairs = ", ".join(f"{kotlin_quote(code)} to {kotlin_quote(GLOSSARY[term][code])}" for code in LANGS)
        lines.append(f"        {kotlin_quote(term)} to mapOf({pairs}),")
    lines += ["    )", "}", ""]
    return "\n".join(lines)


missing = [
    f"{key}:{code}"
    for key in STRINGS for code in LANGS
    if not STRINGS[key].get(code, "").strip()
]
if missing:
    raise SystemExit("untranslated: " + ", ".join(missing[:20]))

(REPO / "native/ios/Auspice/Catalogue.swift").write_text(build_swift())
(REPO / "native/android/app/src/main/kotlin/art/lazying/auspice/Catalogue.kt").write_text(build_kotlin())
print(f"{len(STRINGS)} keys × {len(LANGS)} languages written into both apps")

CONTENT = json.loads((REPO / "i18n/app/content.json").read_text())
for source, translations in CONTENT.items():
    assert set(translations) == set(LANGS), f"Missing language: {source}"
    placeholders = sorted(re.findall(r"\{\d+\}", source))
    for code, translated in translations.items():
        assert translated.strip(), f"Empty translation: {source}:{code}"
        assert sorted(re.findall(r"\{\d+\}", translated)) == placeholders, f"Changed placeholders: {source}:{code}"
for relative in ["native/ios/Auspice/Resources", "native/android/app/src/main/assets"]:
    destination = REPO / relative / "auspice-content.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(CONTENT, ensure_ascii=False, separators=(",", ":")) + "\n")
print(f"{len(CONTENT)} reading phrases × {len(LANGS)} languages bundled into both apps")

# The PWA uses the same translations for deterministic reading terms.
web = REPO / 'src/generated/reading-content.json'
web.parent.mkdir(exist_ok=True)
web.write_text(json.dumps({source: {code: row[code] for code in ['en', 'zh-Hans']}
    for source, row in {**GLOSSARY, **CONTENT}.items()}, ensure_ascii=False, separators=(',', ':')) + '\n')
