"""Generate the interface strings for both native apps from one catalogue.

The catalogue is `i18n/app/strings.json`; everything the reader sees as
interface chrome lives there, in eleven languages. The traditions' own terms —
宜, 忌, 日主, 甲子, 生气 — deliberately stay in Chinese characters in every
language, because they are the subject rather than the interface, and a reader
looking 宜 up in a book will not find "suitable".

    python3 tools/auspice-build-strings.py
"""
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
CATALOGUE = json.loads((REPO / "i18n/app/strings.json").read_text())
LANGS = CATALOGUE["languages"]
STRINGS = CATALOGUE["strings"]

NAMES = {
    "en": "English", "zh-Hans": "简体中文", "zh-Hant": "繁體中文", "ja": "日本語",
    "ko": "한국어", "vi": "Tiếng Việt", "es": "Español", "fr": "Français",
    "de": "Deutsch", "ru": "Русский", "ar": "العربية",
}
RTL = {"ar"}


def swift_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def kotlin_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'


def build_swift() -> str:
    lines = [
        "// Generated by tools/auspice-build-strings.py from i18n/app/strings.json.",
        "// Edit the catalogue, not this file.",
        "import SwiftUI",
        "",
        "enum Catalogue {",
        "    static let languages: [(code: String, name: String)] = [",
    ]
    for code in LANGS:
        lines.append(f"        ({swift_quote(code)}, {swift_quote(NAMES[code])}),")
    lines += [
        "    ]",
        "",
        f"    static let rightToLeft: Set<String> = [{', '.join(swift_quote(c) for c in sorted(RTL))}]",
        "",
        "    static let table: [String: [String: String]] = [",
    ]
    for key in sorted(STRINGS):
        pairs = ", ".join(f"{swift_quote(code)}: {swift_quote(STRINGS[key][code])}" for code in LANGS)
        lines.append(f"        {swift_quote(key)}: [{pairs}],")
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def build_kotlin() -> str:
    lines = [
        "// Generated by tools/auspice-build-strings.py from i18n/app/strings.json.",
        "// Edit the catalogue, not this file.",
        "package art.lazying.auspice",
        "",
        "object Catalogue {",
        "    val languages: List<Pair<String, String>> = listOf(",
    ]
    for code in LANGS:
        lines.append(f"        {kotlin_quote(code)} to {kotlin_quote(NAMES[code])},")
    lines += [
        "    )",
        "",
        f"    val rightToLeft: Set<String> = setOf({', '.join(kotlin_quote(c) for c in sorted(RTL))})",
        "",
        "    val table: Map<String, Map<String, String>> = mapOf(",
    ]
    for key in sorted(STRINGS):
        pairs = ", ".join(f"{kotlin_quote(code)} to {kotlin_quote(STRINGS[key][code])}" for code in LANGS)
        lines.append(f"        {kotlin_quote(key)} to mapOf({pairs}),")
    lines += ["    )", "}", ""]
    return "\n".join(lines)


missing = [
    f"{key}:{code}"
    for key in STRINGS for code in LANGS
    if not STRINGS[key].get(code, "").strip()
]
if missing:
    raise SystemExit("untranslated: " + ", ".join(missing[:20]))

(REPO / "native/ios/Auspice/Catalogue.swift").write_text(build_swift())
(REPO / "native/android/app/src/main/kotlin/art/lazying/auspice/Catalogue.kt").write_text(build_kotlin())
print(f"{len(STRINGS)} keys × {len(LANGS)} languages written into both apps")
