#!/usr/bin/env python3
"""Generate src/lib/hant.ts: a Simplified→Traditional character table covering
every CJK character used in the engine data, so Traditional and Cantonese
interfaces show 寶劍國王 rather than 宝剑国王 without shipping a full OpenCC
dictionary. Rerun after adding practice data."""
import pathlib, re
import opencc

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = list((ROOT / 'src' / 'engines').rglob('*.ts')) + [ROOT / 'src' / 'lib' / 'reading.ts']
chars = set()
for path in SOURCES:
    if path.name == 'hant.ts':
        continue
    chars.update(re.findall(r'[一-鿿]', path.read_text()))
converter = opencc.OpenCC('s2t')
pairs = sorted((c, converter.convert(c)) for c in chars if converter.convert(c) != c)
lines = ['// Generated by tools/gen-hant.py; do not edit by hand.',
         'const TABLE: Record<string, string> = {']
lines += [f"  '{s}': '{t}'," for s, t in pairs]
lines += ['}', '',
          '/** Simplified → Traditional for the characters used in the engine data. */',
          'export function toHant(text: string): string {',
          "  let out = ''",
          '  for (const char of text) out += TABLE[char] ?? char',
          '  return out',
          '}', '']
(ROOT / 'src' / 'lib' / 'hant.ts').write_text('\n'.join(lines))
print(f'{len(pairs)} characters mapped from {len(chars)} distinct')
